/**
 * Classification and routing — determines where transcripts should be saved
 * based on attendees, email domains, calendar metadata, and content heuristics.
 */

import { join } from 'path';
import {
  GITHUB_ROOT,
  KEVIN_COACHING_TRANSCRIPTS,
  CHRISTINA_COACHING_TRANSCRIPTS,
  MONDO_ZEN_COACHING_TRANSCRIPTS,
  PERSONAL_TRANSCRIPTS,
  TESTBOARD_TRANSCRIPTS,
} from './config.js';
import type {
  Attendee,
  CalendarMeta,
  ClassificationContext,
  ClassificationResult,
  ClassificationRule,
} from './types.js';

// ============================================================================
// ROUTING RULES
// Priority: 1) Coaching clients  2) Cian's account  3) Default to CTCI
// ============================================================================

export const COACHING_RULES: ClassificationRule[] = [
  // Christina coaching (uses personal gmail or ctci account)
  (ctx) => {
    if (ctx.emails.includes('christina3lane@gmail.com')) {
      return { targetDir: CHRISTINA_COACHING_TRANSCRIPTS, reason: 'coaching:christina_email' };
    }
    if (ctx.gcalTitle.includes('christina lane and cian') && ctx.gcalDescription.includes('zen transurfing')) {
      return { targetDir: CHRISTINA_COACHING_TRANSCRIPTS, reason: 'coaching:christina_gcal' };
    }
    return null;
  },
  // Kevin coaching (uses personal or ctci account)
  (ctx) => {
    const hasKevin =
      ctx.emails.some(e => ['ktlee@pwcpa.ca', 'kevin@kevintlee.ca'].includes(e)) ||
      ctx.emails.some(e => e.includes('kevin') && e.includes('lee')) ||
      ctx.names.some(n => n.includes('kevin') && n.includes('lee'));
    if (hasKevin) return { targetDir: KEVIN_COACHING_TRANSCRIPTS, reason: 'coaching:kevin_attendee' };
    // Title-based fallback: Shadow titles generated by Gemini often start with "Kevin:"
    if (/^kevin[\s:]/i.test(ctx.title) || /^kevin[\s:]/i.test(ctx.gcalTitle)) {
      return { targetDir: KEVIN_COACHING_TRANSCRIPTS, reason: 'coaching:kevin_title' };
    }
    return null;
  },
  // Mondo Zen / Shining Bright Lotus (by attendee domain or title)
  (ctx) => {
    if (ctx.emails.some(e => e.endsWith('@shiningbrightlotus.org') || e.endsWith('@shiningbrightlotus.com') || e.endsWith('@mondozen.org'))) {
      return { targetDir: MONDO_ZEN_COACHING_TRANSCRIPTS, reason: 'coaching:mondo_zen_domain' };
    }
    // Title-based: known recurring series names
    const combined = `${ctx.titleLower} ${ctx.gcalTitle}`;
    if (combined.includes('shining bright lotus') || combined.includes('mondo zen') || combined.includes('fmzf') || combined.includes('clergy council')) {
      return { targetDir: MONDO_ZEN_COACHING_TRANSCRIPTS, reason: 'coaching:mondo_zen_title' };
    }
    return null;
  },
];

// Helper: Determine Ganttsy sub-routing (strategy vs team)
export function classifyGanttsySubRoute(ctx: ClassificationContext): ClassificationResult {
  const ganttsyTeam = ['bart@ganttsy.com', 'rustam@ganttsy.com', 'vergel@ganttsy.com', 'aby@ganttsy.com'];
  const isOneOnOne = ctx.nonself.length === 1 && ctx.nonselfEmails.some(e => ganttsyTeam.includes(e));
  const strategyKeywords = ['strategy', 'interview', 'candidate', 'hiring', 'debrief', 'business', 'investor', 'funding', 'pitch', '1:1', '1-1', 'one on one'];
  const combined = `${ctx.titleLower} ${ctx.gcalTitle}`;
  const hasStrategyKeyword = strategyKeywords.some(k => combined.includes(k));

  if (isOneOnOne || hasStrategyKeyword) {
    return { targetDir: join(GITHUB_ROOT, 'ganttsy/ganttsy-strategy/transcripts'), reason: 'ganttsy:strategy' };
  }
  return { targetDir: join(GITHUB_ROOT, 'ganttsy/ganttsy-docs/planning/transcripts'), reason: 'ganttsy:team' };
}

// Helper: extract email domain
export function emailDomain(email: string): string {
  const idx = email.indexOf('@');
  return idx >= 0 ? email.slice(idx + 1).toLowerCase() : '';
}

// Domain-based routing: map attendee email domains to destinations
// Order matters — first match wins
const DOMAIN_ROUTES: Array<{
  domains: string[];
  route: (ctx: ClassificationContext) => ClassificationResult;
}> = [
  // Ganttsy
  {
    domains: ['ganttsy.com'],
    route: (ctx) => classifyGanttsySubRoute(ctx),
  },
  // CopperTeams
  {
    domains: ['copperteams.ai'],
    route: () => ({ targetDir: join(GITHUB_ROOT, 'copperteams/ct-docs/planning/transcripts'), reason: 'domain:copperteams' }),
  },
  // NVS (includes Telus as NVS client)
  {
    domains: ['newvaluegroup.com', 'telus.com'],
    route: () => ({ targetDir: join(GITHUB_ROOT, 'nvs/nvs-docs/transcripts'), reason: 'domain:nvs' }),
  },
  // Testboard
  {
    domains: ['thetestboard.com'],
    route: () => ({ targetDir: TESTBOARD_TRANSCRIPTS, reason: 'domain:testboard' }),
  },
];

export function classifyTarget(title: string, attendees: Attendee[], gcalMeta: CalendarMeta | null = null): ClassificationResult {
  const nonself = attendees.filter(a => !a.isSelf);
  const ctx: ClassificationContext = {
    title,
    titleLower: (title || '').toLowerCase(),
    emails: attendees.filter(a => a.email).map(a => a.email),
    names: attendees.filter(a => a.name).map(a => a.name.toLowerCase()),
    nonself,
    nonselfEmails: nonself.filter(a => a.email).map(a => a.email),
    nonselfNames: nonself.filter(a => a.name).map(a => a.name.toLowerCase()),
    gcalTitle: (gcalMeta?.event_title || '').toLowerCase(),
    gcalDescription: (gcalMeta?.event_description || '').toLowerCase(),
    gcalCalendarId: (gcalMeta?.calendar_id || '').toLowerCase(),
  };

  // 1) Coaching clients (highest priority — includes Kevin, Christina, Mondo Zen)
  for (const rule of COACHING_RULES) {
    const result = rule(ctx);
    if (result) return result;
  }

  // 2) Domain-based routing: check ALL attendee email domains (from event + description)
  //    This catches Cian's org accounts AND third-party attendees
  const allDomains = new Set(ctx.emails.map(emailDomain).filter(Boolean));
  for (const dr of DOMAIN_ROUTES) {
    if (dr.domains.some(d => allDomains.has(d))) {
      return dr.route(ctx);
    }
  }

  // 3) Personal: no non-self attendees means no business context detected
  if (ctx.nonselfEmails.length === 0) {
    return { targetDir: PERSONAL_TRANSCRIPTS, reason: 'personal:no_attendees' };
  }

  // 4) Default to CTCI (has attendees but no domain match — likely a new/unknown client)
  return { targetDir: join(GITHUB_ROOT, 'cognitivetech/ctci-docs/transcripts'), reason: 'default:ctci' };
}

export function isLikelyKevinCoachingFromContent(title: string, transcriptText: string): boolean {
  const t = (title || '').toLowerCase();
  const genericTitle = /^conversation\s+\d+$/i.test(title || '');
  if (!genericTitle && !t.includes('coaching')) return false;

  const blob = transcriptText.toLowerCase();

  const signals = [
    'black hand',
    'als',
    'pwa',
    'cpa',
    'peter',
    'gratitude practice',
    'switch to bi-weekly',
    'container'
  ];

  const hits = signals.filter(s => blob.includes(s)).length;
  return hits >= 2;
}
